spring.application.name=principal
server.port=9090

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=principal

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
